apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service-deployment
  labels:
    app: consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-service
  template:
    metadata:
      labels:
        app: consumer-service
    spec:
      containers:
        - name: consumer-service
          image: am17docker/iotclient
          ports:
            - containerPort: 8070
          env:
            - name: spring.application.name
              value: "consumer-service"
            - name: pulsar.service-url
              value: "pulsar://pulsar:6650"
            - name: server.port
              value: "8070"
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service-service
spec:
  selector:
    app: consumer-service
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070